app:
  name: item-pdp-service
  version: 1.0.0
  environment: development

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: item_pdp_db
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m
  migrations_path: file://migrations

log:
  level: info
  format: json 